### ISSUE TITLE
Remove duplicate/mislabeled styles

### ISSUE THREAD

**Issue by RaphyRaph** [sigtm/sketch-style-libraries#6]
would be great to parse styles by properties and clean/merge them automatically

**Comment by sigtm** [comment]
Yeah I've only briefly looked into this, but there was no obvious trivial way to add that at the time. Just to make sure I understand your use case, in what situation(s) does this tend to be an issue? Are they accidental duplicates?

**Comment by jessedodds** [comment]
If it's anything like what I've been running into when working on components in individual files, then merging those into our master design system file, here's what I've run into:

- If i don't remove styles from text/objects before pasting into the main file, it'll often create duplicate text styles. This is super annoying as there's no way to see what symbols/layers are using which styles easily, meaning I generally have to modify one of the duplicates so it's more easily identifiable (bright color)
- The alternative is to remove all shared styles before copy/pasting into the master file, then re-applying the styles in there — either way, there's wasted time.

Having the ability to remove or merge duplicate styles would be a godsend.

**Comment by sigtm** [comment]
Agreed, that would indeed be pretty handy. So from what I understand, the duplicate styles would often have the same name?

Just asking cause it might be easier to merge styles by the same name, than to reliably compare all their properties. So that's a feature I'd probably be able to get out quicker. I'll look into it :)

**Comment by seandellis** [comment]
@sigtm I'd love this feature as well.

Yes, my duplicate styles typically have the same name. 

You might take a look at [Sketch Fix Styles](https://github.com/dinozavrix/sketch_fix_styles) for reference. It supported the ability to merge Text Styles with the same name, but it no longer works in Sketch 45+.

**Comment by RaphyRaph** [comment]
There are 2 use cases for duplicate styles: 
- I have a style with the same properties but the name has been updated in the library - in that case I expect the style name to be updated while keeping the text attributions (i.e. the layers with the old style should still be applied, but with the new name)
- I have a style with the same name but different properties - in this situation the style should be deleted

**Comment by sigtm** [comment]
Thanks for the tip @seandellis! That plugin looks easy enough to replicate (famous last words). It assumes the styles you want to merge have identical names and properties, so it just picks a random one to keep and removes the rest.

Otherwise you'd need a comparison step for picking which one to use, which is a bunch more complexity. I'll stick to what I think I can release reasonably quickly, which should cover most use cases anyway.

@RaphyRaph Updating style names that have changed in the source file is a bit trickier, but yeah that's on my radar too. It probably means storing some form of change log to apply the changes next time you pull from that document, since I'm not sure style IDs (which are separate from their names) can be reliably used for matching styles across documents. All in all, a fair few unknowns there so I'll do my best but can't promise anything!

Updating styles by the same name, and deleting styles that don't exist, is already supported :)

**Comment by sigtm** [comment]
That was surprisingly straightforward actually. I'll release the new version in the morning so I'm not asleep if someone immediately finds an unforeseen bug :)

In the meantime, if anyone is feeling adventurous you can already get it on the feature/merge-styles branch:

https://github.com/sigtm/sketch-style-libraries/tree/feature/merge-styles

**Comment by sigtm** [comment]
Shipped!

**Comment by jessedodds** [comment]
Just wanted to chime in and thank you for your openness and responsiveness to the community. Killing it! Thank you :)

**Comment by seandellis** [comment]
Awesome! Thanks for adding this feature. It's a huge lifesaver.

I use a lot of complex nested styles and was surprised by the number of styles that were merged. 

It would be great if the plugin showed a text list of the styles that it's about to merge with the option to Cancel or Merge.
